---
# Site details
site_name: 'AXE: The Cloud Hatchet'
site_description: Just enough to get you started
site_author: Hugh Mooney

# Source code repo
repo_url: 'https://github.com/kxseven/axe'

# Style and Theme
theme: material
theme_dir: 'docs/theme/material'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/kxseven'
  feature:
    tabs: false
  palette:
    primary: 'deep purple'
    accent: 'deep orange'
  repo_icon: 'github'
  logo: 'media/images/logo_icon_w.png'

extra_css:
    - css/theme_extra.css


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Sitemap
pages:
- 'Getting Started':
  - 'Overview': 'index.md'
  - 'Get AXE': 'content/user-guide/getaxe.md'
  - 'Install AXE': 'content/user-guide/installing.md'
  - 'Using AXE': 'content/user-guide/general.md'
  - 'Troubleshooting': 'content/user-guide/troubleshooting.md'
- 'AXE Sub-Commands':
  - 'auth-list-keys': 'content/commands/axe-auth-list-keys.md'
  - 'auth-report': 'content/commands/axe-auth-report.md'
  - 'dump-account': 'content/commands/axe-dump-account.md'
  - 'inventory-report': 'content/commands/axe-inventory-report.md'
  - 'kms-key-list': 'content/commands/axe-kms-key-list.md'
  - 'list': 'content/commands/axe-list.md'
  - 's3-bucket-size': 'content/commands/axe-s3-bucket-size.md'
  - 'scp': 'content/commands/axe-scp.md'
  - 'sg-add': 'content/commands/axe-sg-add.md'
  - 'ssh': 'content/commands/axe-ssh.md'
  - 'subnet-claim-ip': 'content/commands/axe-subnet-claim-ip.md'
  - 'token-krb5formauth-create': 'content/commands/axe-token-krb5formauth-create.md'
  - 'token-mfaauth-create': 'content/commands/axe-token-mfaauth-create.md'
  - 'vpc-viz': 'content/commands/axe-vpc-viz.md'
  - 'whoami': 'content/commands/axe-whoami.md'
- 'For Developers/Contributers':
  - 'Contribution Guide': 'contributing.md'
  - 'The axeutils lib': 'content/dev-guide/axeutils.md'
- 'About':
  - 'Release Notes': 'content/about/release-notes.md'
